/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/awards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Awards */
        get: operations["awards_api_awards_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Audit */
        post: operations["create_audit_api_audits_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audits/{audit_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Poll */
        get: operations["poll_api_audits__audit_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audits/{audit_id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer */
        post: operations["answer_api_audits__audit_id__answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audits/{audit_id}/verdicts/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide */
        post: operations["decide_api_audits__audit_id__verdicts__code__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audits/{audit_id}/report.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report */
        get: operations["report_api_audits__audit_id__report_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audits/{audit_id}/letter/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Letter */
        get: operations["letter_api_audits__audit_id__letter__code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Answer */
        Answer: {
            /** Question Id */
            question_id: string;
            /** Answer */
            answer: string;
        };
        /** AuditCreated */
        AuditCreated: {
            /** Audit Id */
            audit_id: string;
        };
        /** AuditJob */
        AuditJob: {
            /** Audit Id */
            audit_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "awaiting_input" | "complete" | "failed";
            progress: components["schemas"]["Progress"];
            result?: components["schemas"]["AuditResult"] | null;
            pending_question?: components["schemas"]["Question"] | null;
            /** Error */
            error?: string | null;
            /**
             * Preview
             * @default true
             */
            preview: boolean;
        };
        /** AuditResult */
        AuditResult: {
            /** Business */
            business: string;
            /** Verdicts */
            verdicts: components["schemas"]["Verdict"][];
            summary: components["schemas"]["Summary"];
        };
        /** Award */
        Award: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Preview
             * @default true
             */
            preview: boolean;
        };
        /** Body_create_audit_api_audits_post */
        Body_create_audit_api_audits_post: {
            /** Paycodes */
            paycodes: string;
            /** Payruns */
            payruns: string;
            /** Award Id */
            award_id: string;
            /**
             * Mode
             * @default full
             * @enum {string}
             */
            mode: "keyword" | "no_rag" | "classifier" | "agent" | "full";
        };
        /** Citation */
        Citation: {
            /** Clause */
            clause: string;
            /** Text */
            text: string;
            /** Url */
            url?: string | null;
        };
        /** Decision */
        Decision: {
            /**
             * Action
             * @enum {string}
             */
            action: "approve" | "override";
            /**
             * Treatment
             * @enum {string}
             */
            treatment: "yes" | "no" | "unclear";
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Letter */
        Letter: {
            /** Code */
            code: string;
            /** Text */
            text: string;
            /**
             * Draft
             * @default true
             */
            draft: boolean;
        };
        /** Progress */
        Progress: {
            /** Completed */
            completed: number;
            /** Total */
            total: number;
            /** Message */
            message: string;
        };
        /** Question */
        Question: {
            /** Id */
            id: string;
            /** Code */
            code: string;
            /** Text */
            text: string;
            /** Context */
            context: string;
        };
        /** Step */
        Step: {
            /** Tool */
            tool: string;
            /** Summary */
            summary: string;
        };
        /** Summary */
        Summary: {
            /** Shortfall */
            shortfall: number;
            /** Overpayment */
            overpayment: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Verdict */
        Verdict: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "correct" | "under" | "over" | "review";
            /**
             * Counts Towards Super
             * @enum {string}
             */
            counts_towards_super: "yes" | "no" | "unclear";
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "high" | "medium" | "low";
            /** Annual Impact */
            annual_impact: number;
            /** Reasoning */
            reasoning: string;
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /** Steps */
            steps: components["schemas"]["Step"][];
            /** Verifier */
            verifier: string;
            decision?: components["schemas"]["Decision"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    awards_api_awards_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Award"][];
                };
            };
        };
    };
    create_audit_api_audits_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_audit_api_audits_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    poll_api_audits__audit_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                audit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_api_audits__audit_id__answer_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                audit_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Answer"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_api_audits__audit_id__verdicts__code__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                audit_id: string;
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Decision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Verdict"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_api_audits__audit_id__report_csv_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                audit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    letter_api_audits__audit_id__letter__code__get: {
        parameters: {
            query?: {
                download?: boolean;
            };
            header?: never;
            path: {
                audit_id: string;
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Letter"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
