/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/awards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Awards */
        get: operations["list_awards_api_awards_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Samples */
        get: operations["list_samples_api_samples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/samples/{business_id}/paycodes.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sample Paycodes */
        get: operations["get_sample_paycodes_api_samples__business_id__paycodes_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/samples/{business_id}/payruns.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sample Payruns */
        get: operations["get_sample_payruns_api_samples__business_id__payruns_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Audit */
        post: operations["create_audit_api_audits_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audits/{audit_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Audit */
        get: operations["get_audit_api_audits__audit_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audits/{audit_id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer Audit Question */
        post: operations["answer_audit_question_api_audits__audit_id__answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audits/{audit_id}/verdicts/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Verdict */
        post: operations["set_verdict_api_audits__audit_id__verdicts__code__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audits/{audit_id}/report.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report Csv */
        get: operations["get_report_csv_api_audits__audit_id__report_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audits/{audit_id}/letter/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Letter */
        get: operations["get_letter_api_audits__audit_id__letter__code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{full_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serve Spa
         * @description Catch-all so a hard refresh on a client-side route (e.g. /results) still works.
         */
        get: operations["serve_spa__full_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnswerRequest */
        AnswerRequest: {
            /** Question Id */
            question_id: string;
            /** Answer */
            answer: string;
        };
        /** AuditCreateResponse */
        AuditCreateResponse: {
            /** Audit Id */
            audit_id: string;
        };
        /** AuditProgress */
        AuditProgress: {
            /** Total Codes */
            total_codes: number;
            /** Processed Codes */
            processed_codes: number;
            /** Current Step */
            current_step?: string | null;
        };
        /**
         * AuditResult
         * @description What GET /api/audits/{id} returns — partial while running, full once complete.
         */
        AuditResult: {
            /** Audit Id */
            audit_id: string;
            /** Award Id */
            award_id: string;
            status: components["schemas"]["AuditStatus"];
            progress: components["schemas"]["AuditProgress"];
            /**
             * Verdicts
             * @default []
             */
            verdicts: components["schemas"]["CodeVerdict"][];
            pending_question?: components["schemas"]["ClarifyingQuestion"] | null;
            /** Error */
            error?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * AuditStatus
         * @enum {string}
         */
        AuditStatus: "queued" | "running" | "awaiting_input" | "complete" | "failed";
        /** AwardOption */
        AwardOption: {
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** Body_create_audit_api_audits_post */
        Body_create_audit_api_audits_post: {
            /** Paycodes */
            paycodes: string;
            /** Payruns */
            payruns: string;
            /** Award Id */
            award_id: string;
            /**
             * Mode
             * @default full
             * @enum {string}
             */
            mode: "keyword" | "no_rag" | "classifier" | "agent" | "full";
        };
        /**
         * Citation
         * @description A passage the classifier or investigator relied on.
         */
        Citation: {
            /** Source */
            source: string;
            /** Reference */
            reference: string;
            /** Url */
            url?: string | null;
            /** Retrieved Date */
            retrieved_date?: string | null;
            /** Text */
            text?: string | null;
        };
        /**
         * ClarifyingQuestion
         * @description A specific, answerable question the agent asks the bookkeeper (spec section 6.5).
         */
        ClarifyingQuestion: {
            /** Id */
            id: string;
            /** Code */
            code: string;
            /** Question */
            question: string;
            /** Context */
            context?: string | null;
        };
        /**
         * Classification
         * @description Structured output of the classifier for one pay code (spec section 6.2).
         */
        Classification: {
            /** Code */
            code: string;
            /** Normalised Name */
            normalised_name: string;
            /** Ato Category */
            ato_category: string;
            /**
             * Counts Towards Super
             * @enum {string}
             */
            counts_towards_super: "yes" | "no" | "unclear";
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "high" | "medium" | "low";
            /**
             * Citations
             * @default []
             */
            citations: components["schemas"]["Citation"][];
            /** Reasoning */
            reasoning: string;
            /** Question For Reviewer */
            question_for_reviewer?: string | null;
        };
        /**
         * CodeVerdict
         * @description The final, reviewable verdict for one pay code.
         */
        CodeVerdict: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "correct" | "should_count" | "counts_but_shouldnt" | "needs_review";
            classification: components["schemas"]["Classification"];
            /**
             * Investigation
             * @default []
             */
            investigation: components["schemas"]["InvestigationStep"][];
            /** Verifier Agreed */
            verifier_agreed?: boolean | null;
            impact?: components["schemas"]["ImpactResult"] | null;
            pending_question?: components["schemas"]["ClarifyingQuestion"] | null;
            /** Reviewer Decision */
            reviewer_decision?: ("approved" | "overridden") | null;
            /** Override Note */
            override_note?: string | null;
            /** Overridden Counts Towards Super */
            overridden_counts_towards_super?: ("yes" | "no" | "unclear") | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ImpactResult
         * @description Exact dollar impact of one misclassified code (spec section 6.6). Always plain Python.
         */
        ImpactResult: {
            /** Code */
            code: string;
            /**
             * Direction
             * @enum {string}
             */
            direction: "should_count_not_counted" | "counts_should_not";
            /** Annual Amount */
            annual_amount: number;
            /** Super Amount */
            super_amount: number;
            /** Max Penalty Uplift */
            max_penalty_uplift?: number | null;
            /** Note */
            note: string;
        };
        /**
         * InvestigationStep
         * @description One step of the investigator agent's bounded reasoning loop (spec section 6.3).
         */
        InvestigationStep: {
            /** Step Number */
            step_number: number;
            /**
             * Tool
             * @enum {string}
             */
            tool: "get_payment_history" | "search_ato_guidance" | "search_award" | "calculate_impact" | "ask_bookkeeper";
            /** Input */
            input: {
                [key: string]: unknown;
            };
            /** Output */
            output: string;
            citation?: components["schemas"]["Citation"] | null;
        };
        /** LetterResponse */
        LetterResponse: {
            /** Code */
            code: string;
            /** Subject */
            subject: string;
            /** Body */
            body: string;
            /**
             * Draft
             * @default true
             */
            draft: boolean;
            /**
             * Fix Steps
             * @default []
             */
            fix_steps: string[];
            /**
             * Catch Up Summary
             * @default
             */
            catch_up_summary: string;
        };
        /**
         * SampleBusiness
         * @description A bundled example paycodes.csv/payruns.csv pair a reviewer can load with one
         *     click instead of sourcing their own files (spec: bundled sample data for demoing).
         */
        SampleBusiness: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Award Id */
            award_id: string;
            /** Paycode Count */
            paycode_count: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerdictRequest */
        VerdictRequest: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "approved" | "overridden";
            /** Note */
            note?: string | null;
            /** Overridden Counts Towards Super */
            overridden_counts_towards_super?: ("yes" | "no" | "unclear") | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_awards_api_awards_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AwardOption"][];
                };
            };
        };
    };
    list_samples_api_samples_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleBusiness"][];
                };
            };
        };
    };
    get_sample_paycodes_api_samples__business_id__paycodes_csv_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sample_payruns_api_samples__business_id__payruns_csv_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                business_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_audit_api_audits_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_audit_api_audits_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_audit_api_audits__audit_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                audit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_audit_question_api_audits__audit_id__answer_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                audit_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_verdict_api_audits__audit_id__verdicts__code__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                audit_id: string;
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerdictRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeVerdict"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_csv_api_audits__audit_id__report_csv_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                audit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_letter_api_audits__audit_id__letter__code__get: {
        parameters: {
            query?: {
                download?: boolean;
            };
            header?: never;
            path: {
                audit_id: string;
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LetterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    serve_spa__full_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                full_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
